apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: aceest
        image: 095523581136.dkr.ecr.ap-south-2.amazonaws.com/aceest-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
